### ISSUE TITLE
Override method with generic array argument generated with incorrect type

### ISSUE THREAD

**Issue by PaulWagener** [birdrides/mockingbird#126] opened 2020-05-23 07:14 UTC
The generator fails to handle the case where a derived class overrides a method with a generic type in its signature.

Minimal example:

````Swift
class Concrete {
}

class Base<T> {
    func method(withArg: T) {
    }
}

class Derived: Base<Concrete> {
    override func method(withArg: Concrete) {
    }
}
````
The generated code this produces:

````Swift

  // MARK: Mocked `method`(`withArg`: Mocky.Concrete)

  public override func `method`(`withArg`: Mocky.Concrete) -> Void {
    let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "`method`(`withArg`: Mocky.Concrete) -> Void", arguments: [Mockingbird.ArgumentMatcher(`withArg`)])
    mockingContext.didInvoke(invocation) { () -> Void in
      let implementation = stubbingContext.implementation(for: invocation)
      if let concreteImplementation = implementation as? (Mocky.Concrete) -> Void {
        concreteImplementation(`withArg`)
      } else if let concreteImplementation = implementation as? () -> Void {
        concreteImplementation()
      }
    }
  }

  public func `method`(`withArg`: @escaping @autoclosure () -> Mocky.Concrete) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (Mocky.Concrete) -> Void, Void> {
    let arguments: [Mockingbird.ArgumentMatcher] = [Mockingbird.resolve(`withArg`)]
    let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "`method`(`withArg`: Mocky.Concrete) -> Void", arguments: arguments)
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (Mocky.Concrete) -> Void, Void>(mock: self, invocation: invocation)
  }

  // MARK: Mocked `method`(`withArg`: Mocky.Concrete)

  public override func `method`(`withArg`: Mocky.Concrete) -> Void {
    let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "`method`(`withArg`: Mocky.Concrete) -> Void", arguments: [Mockingbird.ArgumentMatcher(`withArg`)])
    mockingContext.didInvoke(invocation) { () -> Void in
      let implementation = stubbingContext.implementation(for: invocation)
      if let concreteImplementation = implementation as? (Mocky.Concrete) -> Void {
        concreteImplementation(`withArg`)
      } else if let concreteImplementation = implementation as? () -> Void {
        concreteImplementation()
      }
    }
  }

  public func `method`(`withArg`: @escaping @autoclosure () -> Mocky.Concrete) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (Mocky.Concrete) -> Void, Void> {
    let arguments: [Mockingbird.ArgumentMatcher] = [Mockingbird.resolve(`withArg`)]
    let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "`method`(`withArg`: Mocky.Concrete) -> Void", arguments: arguments)
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (Mocky.Concrete) -> Void, Void>(mock: self, invocation: invocation)
  }
````
Xcode can't compile this because 

````Swift 
public override func `method`(`withArg`: Mocky.Concrete) -> Void {
````

is generated twice and it fails with a `method(withArg:) has already been overridden`

## Environment

* CLI version: 0.12.0
* Swift version: 5.2.2
* Xcode version: 11.4.1
* Installed via Cocoapods
* XCTest framework

**Comment by PaulWagener** [comment] 2020-05-23 07:38
Just found out that the minimal example doesn't even involve generics. The following example also produces a duplicate method in the generated code:

````Swift

class Base {
    func method(withArg: UInt) {
    }
}


class Derived: Base {
    override func method(withArg: UInt) {
    }
}
````

**Comment by andrewchang-bird** [comment] 2020-05-23 07:58
Thanks for reporting, Paul! This regression should be fixed by #119. The original plan in the #118 issue was to wait until the 0.13 release, but since this extends to declarations in class mocks we’ll push out a patch on Monday.

**Comment by PaulWagener** [comment] 2020-05-24 11:05
Thanks for the quick fix. I can confirm that the duplicate override method has been fixed when using the latest code in master.

However another issue has still remained with regards to overriding methods with generics.
Take for example this example code:

````Swift
class Concrete {
}

class Base<T> {
    func method(vertices: [T]) {
    }
}

class Derived: Base<Concrete> {
}
````

It results in the following generated code:

````Swift
public final class DerivedMock: Mocky.Derived, Mockingbird.Mock {

  ...

  // MARK: Mocked `method`(`vertices`: [T])

  public override func `method`(`vertices`: [T]) -> Void {
    let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "`method`(`vertices`: [T]) -> Void", arguments: [Mockingbird.ArgumentMatcher(`vertices`)], returnType: Swift.ObjectIdentifier((Void).self))
    mockingContext.didInvoke(invocation) { () -> Void in
      let implementation = stubbingContext.implementation(for: invocation)
      if let concreteImplementation = implementation as? ([T]) -> Void {
        concreteImplementation(`vertices`)
      } else if let concreteImplementation = implementation as? () -> Void {
        concreteImplementation()
      }
    }
  }
  ...
}
````

This results in the error `Use of undeclared type 'T'`. The expected generated code would use the `Concrete` type here. 

Interestingly it **does** generate the correct code when the type parameter isn't an array

I've tested this on https://github.com/birdrides/mockingbird/commit/a246a830a288223a21c2c2065adf6f77845e66fd (master)

**Comment by andrewchang-bird** [comment] 2020-05-24 11:54
Thanks for the update!

The latest issue is caused by the type specializer not working recursively on type declarations. There isn’t a great workaround for this right now, but I’ll look into it for 0.13.

**Closed** 2020-05-29 21:12 UTC
Labels: generator bug, reproducible
