### ISSUE TITLE
Swift concurrency async/await support

### ISSUE THREAD

**Issue by paul1893** [birdrides/mockingbird#229] opened 2021-09-08 15:04 UTC
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

With Swift 5.5 and iOS 15, we can use the new swift concurrency (async/await) which seems not yet handled by the generator.
We can write functions like:
- `func sendConcurrently() async -> String`
- `func sendConcurrently() async throws -> String`

It would be great to handle this new syntax.

### Generator Bugs

**1. A minimal example of the original source**
For example, starting a new project and adding this protocol & class
```swift
public protocol MyAppProtocol {
    @available(iOS 15.0.0, *)
    func sendConcurrently() async -> String
    func send() -> String
}


open class MyAppImplementation: MyAppProtocol {

   @available(iOS 15.0.0, *)
    public func sendConcurrently() async -> String {
        "Hello Concurrent World!"
    }
    
    public func send() -> String {
        "Hello World!"
    }
}
```

**2. The actual mocking code generated**
will generate this

```swift
// MARK: - Mocked MyAppImplementation
...
  // MARK: Mocked `sendConcurrently`()
  public override func `sendConcurrently`() -> String {  // /!\ error: Method does not override any method from its superclass
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`sendConcurrently`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> String { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`sendConcurrently`() // /!\ error: 'async' call in a function that does not support concurrency
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: String = mkbObject.`sendConcurrently`() // /!\ error: 'async' call in a function that does not support concurrency
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (String).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `sendConcurrently`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String>(mock: self, invocation: Mockingbird.SwiftInvocation(selectorName: "`sendConcurrently`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self)))
  }

// MARK: - Mocked MyAppProtocol
...
  // MARK: Mocked `sendConcurrently`()
  @available(iOS 15.0.0, *)
  public func `sendConcurrently`() -> String {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`sendConcurrently`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> String { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: String = mkbObject.`sendConcurrently`() // /!\ error: 'async' call in a function that does not support concurrency
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (String).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  @available(iOS 15.0.0, *)
  public func `sendConcurrently`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String>(mock: self, invocation: Mockingbird.SwiftInvocation(selectorName: "`sendConcurrently`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self)))
  }
```
- error: Method does not override any method from its superclass
- error: 'async' call in a function that does not support

**3. The expected mocking code that should be generated (or a description)**
I'm not sure of what should be generated (which depends of how it will be implemented) but what I can say is that:
- the generated signature functions should be 
```swift
@available(iOS 15.0.0, *) public func `sendConcurrently`() async -> String
```
which throw away the "Method does not override any method from its superclass" error.
 - not sure about the implementation but may be something like (seems to work on 0.18+):
```swift
// MockingContext.swift
@available(iOS 15.0.0, *)
    func didInvoke<T, I: Invocation>(_ invocation: I, evaluating thunk: (I) async -> T) async -> T {
      // Ensures that the thunk is evaluated prior to recording the invocation.
      defer { didInvoke(invocation) }
      return await thunk(invocation)
    }

// MARK: - Mocked MyAppImplementation
...
// MARK: Mocked `sendConcurrently`()
    @available(iOS 15.0.0, *)
    public override func `sendConcurrently`() async -> String {
        await self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`sendConcurrently`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self))) { invocation async in
            self.mockingbirdContext.recordInvocation(invocation)
            let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: invocation)
            if let mkbImpl = mkbImpl as? () -> String { return mkbImpl() }
            for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: invocation) {
                switch mkbTargetBox.target {
                case .super:
                    return await super.`sendConcurrently`()
                case .object(let mkbObject):
                    guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
                    let mkbValue: String = await mkbObject.`sendConcurrently`()
                    self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
                    return mkbValue
                }
            }
            if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (String).self) { return mkbValue }
            self.mockingbirdContext.stubbing.failTest(for: invocation, at: self.mockingbirdContext.sourceLocation)
        }
    }
    
    public func `sendConcurrently`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String> {
        return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String>(mock: self, invocation: Mockingbird.SwiftInvocation(selectorName: "`sendConcurrently`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self)))
    }


// MARK: - Mocked MyAppProtocol
...
// MARK: Mocked `sendConcurrently`()
    @available(iOS 15.0.0, *)
    public func `sendConcurrently`() async -> String {
        return await self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`sendConcurrently`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self))) { invocation async in
            self.mockingbirdContext.recordInvocation(invocation)
            let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: invocation)
            if let mkbImpl = mkbImpl as? () -> String { return mkbImpl() }
            for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: invocation) {
                switch mkbTargetBox.target {
                case .super:
                    break
                case .object(let mkbObject):
                    guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
                    let mkbValue: String = await mkbObject.`sendConcurrently`()
                    self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
                    return mkbValue
                }
            }
            if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (String).self) { return mkbValue }
            self.mockingbirdContext.stubbing.failTest(for: invocation, at: self.mockingbirdContext.sourceLocation)
        }
    }

  public func `sendConcurrently`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> String, String>(mock: self, invocation: Mockingbird.SwiftInvocation(selectorName: "`sendConcurrently`() -> String", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((String).self)))
  }
```

**Tips for others/waiting support**
On our side (at work), we're staying on 0.17. For the several files we need to handle, we copy/paste wrong generated mocks to a manual-mock file that we maintain and only change the signature to ```@available(iOS 15.0.0, *) public func `sendConcurrently`() async -> String``` which seems enough. (On 0.18+ it requires more works).
Then we exclude those files with `.mockingbird-ignore` from being generated to avoid conflict.

Work's project compile and tests runs without edge cases for now.
```swift
func testExample() async {
    let myProtocol = mock(MyAppProtocol.self)
    given(myProtocol.sendConcurrently()).willReturn("Hello Concurrent World!")
    let result: String = await myProtocol.sendConcurrently()
    XCTAssertEqual(result, "Hello Concurrent World!")
}
```

## Environment

* Mockingbird CLI version: `mockingbird version: 0.18.1`
* Xcode and macOS version (are you running a beta?): `XCode beta 13.0 beta 5 (13A5212g) & macOS BigSur 11.3 (20E232)`
* Swift version: `swift version: 5.5`
* Installation method: `CocoaPods`
* Unit testing framework: `XCTest`
* Does your project use `.mockingbird-ignore`?: `Yes`
* Are you using [supporting source files](https://github.com/birdrides/mockingbird#supporting-source-files)?: `Yes`

**Comment by andrewchang-bird** [comment] 2021-09-09 02:10
Thanks for reporting, Paul. I’m tracking this as part of the Swift 5.5 compatibility tasks. Note that we usually don’t support Xcode betas, although the GM should be pretty soon 🤞

**Comment by jacobhzen** [comment] 2021-10-14 22:52
Any update here? This is breaking iOS 15 apps

**Comment by Allje** [comment] 2022-01-13 14:14
Any update on support for Swift 5.5?

**Comment by andrewchang-bird** [comment] 2022-01-14 00:29
Unfortunately it didn’t make the cut for 0.19 which focused on regressions from Obj-C compatibility, but it’s at the top of the list. It‘s not ideal, but to avoid compilation errors in the interim, you should run the generator in `--prune omit` mode (the default since 0.17) and avoid mocking types that declare async methods.

**Comment by ailtonvivaz** [comment] 2022-01-23 23:17
I've implemented this feature, but the function `public func given(_:Mockable<DeclarationType, InvocationType, ReturnType>)` is not called with async functions.
Instead of this, the signature `public func given<ReturnType>( _: @autoclosure () throws -> ReturnType)` is called even there is the `@_disfavoredOverload` attribute.
```swift
func testExample() async {
    let myProtocol = mock(MyAppProtocol.self)
    given(myProtocol.sendConcurrently()) // ❌ 'async' call in an autoclosure that does not support concurrency
        .willReturn("Hello Concurrent World!")
    let result: String = await myProtocol.sendConcurrently()
    XCTAssertEqual(result, "Hello Concurrent World!")
}
```

**The implementation just works in two scenarios:**
- When I call `public func givenSwift(_: Mockable<DeclarationType, InvocationType, ReturnType>)` directly
```swift
func testExample() async {
    let myProtocol = mock(MyAppProtocol.self)
    givenSwift(myProtocol.sendConcurrently())
        .willReturn("Hello Concurrent World!")
    let result: String = await myProtocol.sendConcurrently()
    XCTAssertEqual(result, "Hello Concurrent World!")
}
```
- Or when I assign to a typed variable:
```swift
func testExample() async {
    let stub: Mockable = asyncProtocol.asyncMethod()
    let myProtocol = mock(MyAppProtocol.self)
    given(stub)
        .willReturn("Hello Concurrent World!")
    let result: String = await myProtocol.sendConcurrently()
    XCTAssertEqual(result, "Hello Concurrent World!")
}
```

I believe there is some bug with the precedence function with async and the `@_disfavoredOverload` is not working well.

**Comment by andrewchang-bird** [comment] 2022-01-24 00:48
@ailtonvivaz Thanks for looking into supporting Swift concurrency. Requiring `givenSwift` to disambiguate the overload is unfortunate but isn’t a blocker in the short term. Once you’re ready to push your changes I’ll investigate if there’s a way to work around this.

**Comment by ailtonvivaz** [comment] 2022-01-25 00:37
I've just submitted a PR with this implementation. I created `givenAsync` and `verifyAsync` to stub and verify. I hope there's any way to workaround this.

**Closed** 2022-01-26 01:41 UTC
Labels: generator bug, reproducible, swift 5.5
