### ISSUE TITLE
Unable get generate file

### ISSUE THREAD

**Issue by DhirajChaudhari** [birdrides/mockingbird#26] opened 2020-01-16 12:13 UTC
can you guide me install and generating mock file. I have it  tried by below way.
**My Used file as below.**
Protocol -> LoginProtocol
Manager -> LoginApiManager
TestFile -> LoginTests
project target -> Login
test target -> LoginTest

 ### **// Below command generate  blur file of generated mocs but cant accessible in project**
 mockingbird install \
  --project Login.xcodeproj \
  --target LoginExample \
  --destination LoginTests

 Can you guide me how to generate  LoginProtocol mocs .

**Comment by andrewchang-bird** [comment] 2020-01-23 19:41
Based on your installation, mocks will generate in the pre-compile build phase for `LoginTests`. If you run (or build) your unit testing bundle you should see the file `MockingbirdMocks/LoginExampleMocks.generated.swift` get generated.

**Comment by andrewchang-bird** [comment] 2020-01-31 22:35
Closing this issue. Please re-open it or join [the Slack](https://slofile.com/slack/birdopensource) if needed.

**Closed by andrewchang-bird** 2020-01-31 22:35 UTC
Labels: JIRA OS-19

**Comment by baksha97-pseg** [comment] 2020-04-09 17:09
I am having the same issue with the transcript: 


```
Showing All Messages
[WARN] Unable to decode the cached target data at /Users/user/Files/iOS/Mobile-iOS/Mobile.xcodeproj/MockingbirdCache/Mobile.lock
```

Any recommendation?

**Comment by user-mobil** [comment] 2020-04-09 17:32
Debugging the generator leads me to find this issue:
`
Showing All Messages
/Users/user/Library/Developer/Xcode/DerivedData/TDA-cgbasagkjrisyeazvvapcienjukt/Build/Intermediates.noindex/TDA.build/Mock-iphonesimulator/TDATests.build/Script-64285976CAF908518AF02F05.sh: line 5:   734 Illegal instruction: 4  mockingbird generate --targets 'TDA' --outputs "${SRCROOT}/MockingbirdMocks/TDAMocks.generated.swift" --support "${SRCROOT}/MockingbirdSupport"

`

**Comment by andrewchang-bird** [comment] 2020-04-09 18:56
@user-mobil What dependency manager are you using? Are you building the CLI from source, or using one of the pre-built artifacts?

**Comment by user-mobil** [comment] 2020-04-09 20:03
Cocoa pods 
```
$ cd Pods/MockingbirdFramework
$ make install-prebuilt
```
It also successfully installs on my own test target.
```
$ mockingbird install \
  --target BirdTests \
  --sources Bird BirdManagers
```

**Comment by andrewchang-bird** [comment] 2020-04-09 20:43
It’s odd that the demo project would work but not your main project. Have you tried `xcode-select` per [this thread](https://github.com/realm/SwiftLint/issues/1466#issuecomment-297265863)? What version of macOS are you running?

**Comment by user-mobil** [comment] 2020-04-09 21:35
Catalina, and yes! I have updated it to the proper .app, since i have it under a different name.

**Comment by andrewchang-bird** [comment] 2020-04-09 23:15
Try building and installing the CLI from source instead:

```
$ cd Pods/MockingbirdFramework
$ make setup-project
$ make install
```

If that doesn’t work, please consider joining [the Slack channel](https://slofile.com/slack/birdopensource) as I’m not able to reproduce this on my end. However, I suspect it’s due to having multiple Xcode toolchains installed.

**Comment by user-mobil** [comment] 2020-04-09 23:58
Hey! Took all day, but I figured it out... it was the `.mockingbird-ignore` file. This project is a bit massive, so what I did was ignore everything but a particular folder I am looking to test. That's an odd error, but I am assuming it's because it was trying to mock some things it wasn't capable of somewhere in here. Thanks for your time and help!

- Travis
